[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "graphs_mburrill"
version = "0.1.0"
description = "A Python library for finding shortest paths in weighted graphs."
readme = "README.md"
requires-python = ">=3.9"
authors = [
    {name = "Mason Burrill"}
]

[tool.setuptools.packages.find]
where = ["src"]